TYPE=VIEW
query=select `studenspayment`.`tbl_class`.`ID` AS `ID`,`studenspayment`.`tbl_class`.`StudyDay` AS `StudyDay` from `studenspayment`.`tbl_class`
md5=bace3feb8301ea5bf7ae0f959bf40d38
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001713119503434167
create-version=2
source=SELECT\n	tbl_class.ID, \n	tbl_class.StudyDay\nFROM\n	tbl_class
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `studenspayment`.`tbl_class`.`ID` AS `ID`,`studenspayment`.`tbl_class`.`StudyDay` AS `StudyDay` from `studenspayment`.`tbl_class`
mariadb-version=100432
