TYPE=VIEW
query=select `studenspayment`.`tbl_class`.`ID` AS `ID`,`studenspayment`.`tbl_class`.`RoomNumber` AS `RoomNumber` from `studenspayment`.`tbl_class`
md5=9edc1b39745c94c3c540c491916869c9
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=0001713188597760655
create-version=2
source=SELECT\n	tbl_class.ID, \n	tbl_class.RoomNumber\nFROM\n	tbl_class
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `studenspayment`.`tbl_class`.`ID` AS `ID`,`studenspayment`.`tbl_class`.`RoomNumber` AS `RoomNumber` from `studenspayment`.`tbl_class`
mariadb-version=100432
