TYPE=VIEW
query=select `studenspayment`.`tbl_payment`.`ID` AS `ID`,`studenspayment`.`tbl_student2`.`S_ChineseName` AS `S_ChineseName`,`studenspayment`.`tbl_student2`.`S_Gender` AS `S_Gender`,`studenspayment`.`tbl_teacher2`.`T_ChineseName` AS `T_ChineseName`,`studenspayment`.`tbl_teacher2`.`T_Gender` AS `T_Gender`,`studenspayment`.`tbl_class2`.`BookLevel` AS `BookLevel`,`studenspayment`.`tbl_class2`.`StudyDate` AS `StudyDate`,`studenspayment`.`tbl_class2`.`StudyTime` AS `StudyTime`,`studenspayment`.`tbl_class2`.`StudyDay` AS `StudyDay`,`studenspayment`.`tbl_class2`.`RoomNumber` AS `RoomNumber`,`studenspayment`.`tbl_class2`.`TuitionFees` AS `TuitionFees`,`studenspayment`.`tbl_payment`.`ManyMonths` AS `ManyMonths`,`studenspayment`.`tbl_payment`.`Discount` AS `Discount`,`studenspayment`.`tbl_payment`.`Payment` AS `Payment`,`studenspayment`.`tbl_payment`.`StartDate` AS `StartDate`,`studenspayment`.`tbl_payment`.`EndDate` AS `EndDate`,`studenspayment`.`tbl_payment`.`PaymentDate` AS `PaymentDate`,`studenspayment`.`tbl_payment`.`InvoiceNumber` AS `InvoiceNumber`,`studenspayment`.`tbl_payment`.`Other` AS `Other`,`studenspayment`.`tbl_payment`.`PayBack` AS `PayBack`,`studenspayment`.`tbl_payment`.`BackMonth` AS `BackMonth` from (((`studenspayment`.`tbl_payment` left join `studenspayment`.`tbl_student2` on(`studenspayment`.`tbl_payment`.`StudenID` = `studenspayment`.`tbl_student2`.`ID`)) left join `studenspayment`.`tbl_class2` on(`studenspayment`.`tbl_payment`.`ClassID` = `studenspayment`.`tbl_class2`.`ID`)) join `studenspayment`.`tbl_teacher2` on(`studenspayment`.`tbl_class2`.`TeacherID` = `studenspayment`.`tbl_teacher2`.`ID`))
md5=2f90e6883385a44945a400128e463c31
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=0001718037419099072
create-version=2
source=SELECT\n	tbl_payment.ID, \n	tbl_student2.S_ChineseName, \n	tbl_student2.S_Gender, \n	tbl_teacher2.T_ChineseName, \n	tbl_teacher2.T_Gender, \n	tbl_class2.BookLevel, \n	tbl_class2.StudyDate, \n	tbl_class2.StudyTime, \n	tbl_class2.StudyDay, \n	tbl_class2.RoomNumber, \n	tbl_class2.TuitionFees, \n	tbl_payment.ManyMonths, \n	tbl_payment.Discount, \n	tbl_payment.Payment, \n	tbl_payment.StartDate, \n	tbl_payment.EndDate, \n	tbl_payment.PaymentDate, \n	tbl_payment.InvoiceNumber, \n	tbl_payment.Other, \n	tbl_payment.PayBack, \n	tbl_payment.BackMonth\nFROM\n	tbl_payment\n	LEFT JOIN\n	tbl_student2\n	ON \n		tbl_payment.StudenID = tbl_student2.ID\n	LEFT JOIN\n	tbl_class2\n	ON \n		tbl_payment.ClassID = tbl_class2.ID\n	INNER JOIN\n	tbl_teacher2\n	ON \n		tbl_class2.TeacherID = tbl_teacher2.ID
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `studenspayment`.`tbl_payment`.`ID` AS `ID`,`studenspayment`.`tbl_student2`.`S_ChineseName` AS `S_ChineseName`,`studenspayment`.`tbl_student2`.`S_Gender` AS `S_Gender`,`studenspayment`.`tbl_teacher2`.`T_ChineseName` AS `T_ChineseName`,`studenspayment`.`tbl_teacher2`.`T_Gender` AS `T_Gender`,`studenspayment`.`tbl_class2`.`BookLevel` AS `BookLevel`,`studenspayment`.`tbl_class2`.`StudyDate` AS `StudyDate`,`studenspayment`.`tbl_class2`.`StudyTime` AS `StudyTime`,`studenspayment`.`tbl_class2`.`StudyDay` AS `StudyDay`,`studenspayment`.`tbl_class2`.`RoomNumber` AS `RoomNumber`,`studenspayment`.`tbl_class2`.`TuitionFees` AS `TuitionFees`,`studenspayment`.`tbl_payment`.`ManyMonths` AS `ManyMonths`,`studenspayment`.`tbl_payment`.`Discount` AS `Discount`,`studenspayment`.`tbl_payment`.`Payment` AS `Payment`,`studenspayment`.`tbl_payment`.`StartDate` AS `StartDate`,`studenspayment`.`tbl_payment`.`EndDate` AS `EndDate`,`studenspayment`.`tbl_payment`.`PaymentDate` AS `PaymentDate`,`studenspayment`.`tbl_payment`.`InvoiceNumber` AS `InvoiceNumber`,`studenspayment`.`tbl_payment`.`Other` AS `Other`,`studenspayment`.`tbl_payment`.`PayBack` AS `PayBack`,`studenspayment`.`tbl_payment`.`BackMonth` AS `BackMonth` from (((`studenspayment`.`tbl_payment` left join `studenspayment`.`tbl_student2` on(`studenspayment`.`tbl_payment`.`StudenID` = `studenspayment`.`tbl_student2`.`ID`)) left join `studenspayment`.`tbl_class2` on(`studenspayment`.`tbl_payment`.`ClassID` = `studenspayment`.`tbl_class2`.`ID`)) join `studenspayment`.`tbl_teacher2` on(`studenspayment`.`tbl_class2`.`TeacherID` = `studenspayment`.`tbl_teacher2`.`ID`))
mariadb-version=100432
